server:
  port: 8761
euaeka:
  instance:
    hostname: eureka-server
  client:
    register-wirh-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka/
